spring.application.name=user-app
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/\u039F\u039D\u039F\u039C\u0391_DATABASE
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
